name: qmcdiffusion
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - torchvision
  - matplotlib
  - scipy
  - pot
  - tensorboardx
  - tqdm
  - h5py
  - pip
  - pip:
    - ema-pytorch